name: Model Training Pipeline

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:
    inputs:
      model_type:
        description: 'Model type to train'
        required: true
        default: 'lightgbm'
        type: choice
        options:
          - lightgbm
          - xgboost

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download training data
      run: |
        # This would download your training data
        # aws s3 cp s3://your-bucket/training-data/ data/raw/ --recursive
        echo "Downloading training data..."
    
    - name: Train model
      run: |
        python scripts/train_model.py --model-type ${{ github.event.inputs.model_type || 'lightgbm' }}
    
    - name: Validate model
      run: |
        python scripts/validate_model.py --model-path models/artifacts/eta_model.pkl
    
    - name: Upload model artifacts
      run: |
        # This would upload your model artifacts
        # aws s3 cp models/artifacts/ s3://your-bucket/models/ --recursive
        echo "Uploading model artifacts..."
    
    - name: Create model registry entry
      run: |
        python scripts/register_model.py --model-path models/artifacts/eta_model.pkl